# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/temp/Desktop/Recruitment/RSA-AES-Encrypted-Chat-Cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/temp/Desktop/Recruitment/RSA-AES-Encrypted-Chat-Cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/temp/Desktop/Recruitment/RSA-AES-Encrypted-Chat-Cpp/CMakeFiles /home/temp/Desktop/Recruitment/RSA-AES-Encrypted-Chat-Cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/temp/Desktop/Recruitment/RSA-AES-Encrypted-Chat-Cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named encryptedChatClient

# Build rule for target.
encryptedChatClient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 encryptedChatClient
.PHONY : encryptedChatClient

# fast build rule for target.
encryptedChatClient/fast:
	$(MAKE) -f CMakeFiles/encryptedChatClient.dir/build.make CMakeFiles/encryptedChatClient.dir/build
.PHONY : encryptedChatClient/fast

#=============================================================================
# Target rules for targets named encryptedChatServer

# Build rule for target.
encryptedChatServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 encryptedChatServer
.PHONY : encryptedChatServer

# fast build rule for target.
encryptedChatServer/fast:
	$(MAKE) -f CMakeFiles/encryptedChatServer.dir/build.make CMakeFiles/encryptedChatServer.dir/build
.PHONY : encryptedChatServer/fast

#=============================================================================
# Target rules for targets named AES

# Build rule for target.
AES: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AES
.PHONY : AES

# fast build rule for target.
AES/fast:
	$(MAKE) -f lib/AES/CMakeFiles/AES.dir/build.make lib/AES/CMakeFiles/AES.dir/build
.PHONY : AES/fast

#=============================================================================
# Target rules for targets named RSA

# Build rule for target.
RSA: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RSA
.PHONY : RSA

# fast build rule for target.
RSA/fast:
	$(MAKE) -f lib/RSA/CMakeFiles/RSA.dir/build.make lib/RSA/CMakeFiles/RSA.dir/build
.PHONY : RSA/fast

#=============================================================================
# Target rules for targets named chatSocket

# Build rule for target.
chatSocket: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chatSocket
.PHONY : chatSocket

# fast build rule for target.
chatSocket/fast:
	$(MAKE) -f lib/chatSocket/CMakeFiles/chatSocket.dir/build.make lib/chatSocket/CMakeFiles/chatSocket.dir/build
.PHONY : chatSocket/fast

example/chat_client.o: example/chat_client.cpp.o

.PHONY : example/chat_client.o

# target to build an object file
example/chat_client.cpp.o:
	$(MAKE) -f CMakeFiles/encryptedChatClient.dir/build.make CMakeFiles/encryptedChatClient.dir/example/chat_client.cpp.o
.PHONY : example/chat_client.cpp.o

example/chat_client.i: example/chat_client.cpp.i

.PHONY : example/chat_client.i

# target to preprocess a source file
example/chat_client.cpp.i:
	$(MAKE) -f CMakeFiles/encryptedChatClient.dir/build.make CMakeFiles/encryptedChatClient.dir/example/chat_client.cpp.i
.PHONY : example/chat_client.cpp.i

example/chat_client.s: example/chat_client.cpp.s

.PHONY : example/chat_client.s

# target to generate assembly for a file
example/chat_client.cpp.s:
	$(MAKE) -f CMakeFiles/encryptedChatClient.dir/build.make CMakeFiles/encryptedChatClient.dir/example/chat_client.cpp.s
.PHONY : example/chat_client.cpp.s

example/chat_server.o: example/chat_server.cpp.o

.PHONY : example/chat_server.o

# target to build an object file
example/chat_server.cpp.o:
	$(MAKE) -f CMakeFiles/encryptedChatServer.dir/build.make CMakeFiles/encryptedChatServer.dir/example/chat_server.cpp.o
.PHONY : example/chat_server.cpp.o

example/chat_server.i: example/chat_server.cpp.i

.PHONY : example/chat_server.i

# target to preprocess a source file
example/chat_server.cpp.i:
	$(MAKE) -f CMakeFiles/encryptedChatServer.dir/build.make CMakeFiles/encryptedChatServer.dir/example/chat_server.cpp.i
.PHONY : example/chat_server.cpp.i

example/chat_server.s: example/chat_server.cpp.s

.PHONY : example/chat_server.s

# target to generate assembly for a file
example/chat_server.cpp.s:
	$(MAKE) -f CMakeFiles/encryptedChatServer.dir/build.make CMakeFiles/encryptedChatServer.dir/example/chat_server.cpp.s
.PHONY : example/chat_server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... encryptedChatClient"
	@echo "... encryptedChatServer"
	@echo "... AES"
	@echo "... RSA"
	@echo "... chatSocket"
	@echo "... example/chat_client.o"
	@echo "... example/chat_client.i"
	@echo "... example/chat_client.s"
	@echo "... example/chat_server.o"
	@echo "... example/chat_server.i"
	@echo "... example/chat_server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

